version: "3.9"



services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: prmanagement
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: springboot-backend
    restart: always
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prmanagement
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    networks:
      - app-network
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge